version: "3"
services:
    api:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - ./api:/api
        environment:
            - DEBUG=1
            - ALLOWED_HOSTS=*
            - DATABASE_URL=postgres://postgres:password@localhost/pct
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
        depends_on:
            - postgres
            
    postgres:
        image: postgres:11
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=pct
        volumes:
            - pg-vol:/var/lib/postgres/data
        ports:
            - "5432:5432"
        
volumes:
    pg-vol: